### ISSUE TITLE
thread 'main' panicked at 'Unable to create Vulkan instance: VkError(ERROR_INCOMPATIBLE_DRIVER)', src/libcore/result.rs:1165

### ISSUE THREAD

**Issue by WhatWithCheeze432** [hecrj/coffee#120]
**Log**:

```
usr@debian:~/code/rust/coffee/examples$ cargo run --example particles --features vulkan,debug --release
   Compiling xcb v0.8.2
   Compiling gfx-backend-vulkan v0.2.3
   Compiling wgpu-native v0.2.6 (https://github.com/gfx-rs/wgpu?rev=5224bb812420e420485ee08ad8cb820695a3e6eb#5224bb81)
   Compiling wgpu v0.2.2 (https://github.com/gfx-rs/wgpu-rs?rev=5522c912f7e2f4f33a1167fb0c8ee4549f066dcf#5522c912)
   Compiling wgpu_glyph v0.3.1 (https://github.com/hecrj/wgpu_glyph?rev=0577e4d2be6b035a14aa0c5d82b143aaf26c1bd3#0577e4d2)
   Compiling coffee v0.4.0-alpha (/home/usr/code/rust/coffee)
    Finished release [optimized] target(s) in 1m 02s
     Running `/home/usr/code/rust/coffee/target/release/examples/particles`
thread 'main' panicked at 'Unable to create Vulkan instance: VkError(ERROR_INCOMPATIBLE_DRIVER)', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
usr@debian:~/code/rust/coffee/examples$ 
```
**Description**: VkError(ERROR_INCOMPATIBLE_DRIVER)', src/libcore/result.rs:1165:5

____________________

**OS**: Debian GNU/Linux

**Cargo Version**: `cargo 1.40.0 (bc8e4c8be 2019-11-22)`

**Comment by WhatWithCheeze432** [comment]
Lutris has some documentation for how to install these drivers:

- https://github.com/lutris/lutris/wiki/Installing-drivers

_____________________

It seems that Debian users using Intel/AMD Graphics can run:

> `sudo apt install mesa-vulkan-drivers`

**Comment by WhatWithCheeze432** [comment]
I am unaware of how or if Windows/MacOS users need to implement something similar.

Feel free to comment instructions or issues with those platforms.
